package com.hospital.management.model;

import jakarta.persistence.*;

@Entity
@Table(name = "admins")
public class Admin {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    @Column(nullable = false, length = 100)
    private String name;
    
    @Column(length = 15)
    private String phone;
    
    @OneToOne
    @JoinColumn(name = "user_id")
    private User user;
    
    // Constructors
    public Admin() {}
    
    public Admin(String name, String phone) {
        this.name = name;
        this.phone = phone;
    }
    
    // Methods from diagram
    public void manageUsers() {
        // Logic to manage users (create, update, delete users)
        System.out.println("Admin " + name + " is managing users");
    }
    
    public String generateReports() {
        // Logic to generate system reports
        return String.format("Report generated by Admin: %s", name);
    }
    
    // Getters and Setters
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
    
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }
    
    public String getPhone() { return phone; }
    public void setPhone(String phone) { this.phone = phone; }
    
    public User getUser() { return user; }
    public void setUser(User user) { this.user = user; }
}
